#!/usr/bin/env python3
"""Cross-platform build script for UMOS Desktop.

Produces a standalone executable:
  - Windows:  UMOS-Desktop.exe (one-file, --windowed by default)
  - macOS:    UMOS-Desktop.app (one-file bundle, --windowed by default)
  - Linux:    UMOS-Desktop (one-file ELF, --windowed does nothing)

Usage:
    python build_exe.py              # build for current platform
    python build_exe.py --console   # include console window
    python build_exe.py --name Foo  # custom binary name
    python build_exe.py --os macos  # cross-build for macOS (if not on macOS,
                                    # requires Xcode SDK installed externally)
"""

from __future__ import annotations

import os
import platform
import subprocess
import sys
from pathlib import Path


def main():
    root = Path(__file__).resolve().parent
    args = sys.argv[1:]
    console = "--console" in args
    custom_name = _parse_flag(args, "--name", "UMOS-Desktop")
    target_os = _parse_flag(args, "--os", sys.platform).lower()

    # Normalise platform names
    if target_os in ("darwin", "macos"):
        target_os = "darwin"
    elif target_os in ("win32", "windows", "win"):
        target_os = "win32"
    elif target_os in ("linux", "linux2"):
        target_os = "linux"

    try:
        import PyInstaller  # noqa
    except ImportError:
        _info("Installing PyInstaller...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])

    sep = ";" if target_os == "win32" else ":"

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", custom_name,
        "--noconfirm",
        "--clean",
        "--onefile",
    ]

    if not console and target_os != "linux":
        cmd.append("--windowed")

    if target_os == "darwin":
        cmd.extend([
            "--osx-bundle-identifier", "com.unimind.os.desktop",
            "--icon", str(root / "assets" / "icon.icns") if (root / "assets" / "icon.icns").exists() else "",
        ])
    elif target_os == "win32":
        icon = root / "assets" / "icon.ico"
        if icon.exists():
            cmd.extend(["--icon", str(icon)])

    # Add data dirs (each as SOURCE{DEST)
    for pkg in ("umos_py", "bridge", "quantum", "gui"):
        src = root / pkg
        if src.is_dir():
            cmd.append(f"--add-data={src}{sep}{pkg}")

    # Hidden imports for dynamic lookups
    for mod in ("umos_py", "bridge", "gui", "quantum"):
        cmd.append(f"--collect-submodules={mod}")

    # Entry point
    cmd.append(str(root / "gui" / "app.py"))

    _info("Running PyInstaller for platform: {}".format(target_os))
    _info("  Command: {}".format(" ".join(cmd)))
    subprocess.check_call(cmd, cwd=root)

    # Report output
    output_name = {
        "win32": "{}.exe".format(custom_name),
        "darwin": "{}.app".format(custom_name),
        "linux": custom_name,
    }.get(target_os, custom_name)
    output = root / "dist" / output_name

    if output.exists():
        size_mb = output.stat().st_size / (1024 * 1024)
        _info("[OK] Built: {} ({:.1f} MB)".format(output, size_mb))
    else:
        _info("[WARN] Expected output not found: {}".format(output))
        dist_dir = root / "dist"
        if dist_dir.exists():
            for p in dist_dir.rglob("*"):
                if p.is_file():
                    _info("  {} ({:.0f} KB)".format(p.relative_to(root), p.stat().st_size / 1024))

    # Generate installer script for the target platform
    if target_os == "win32":
        _gen_innosetup(root, custom_name)
    elif target_os == "darwin":
        _gen_dmg_setup(root, custom_name)
    else:
        _gen_linux_setup(root, custom_name)

    _info("Done.")


# --- helpers ---

def _parse_flag(args: list[str], flag: str, default: str) -> str:
    for i, a in enumerate(args):
        if a == flag and i + 1 < len(args):
            return args[i + 1]
    return default


def _info(msg: str):
    print(msg, file=sys.stderr)


# --- Installer generators ---

def _gen_innosetup(root: Path, name: str):
    iss = root / "UMOS_installer.iss"
    iss.write_text(
        "; UMOS Desktop Installer -- generated by build_exe.py\n"
        "[Setup]\n"
        "AppName=UniMind OS (UMOS) Desktop\n"
        "AppVersion=0.5.0\n"
        "DefaultDirName={{pf}}\\{}\n".format(name) +
        "DefaultGroupName=UMOS\n"
        "UninstallDisplayIcon={{app}}\\{}.exe\n".format(name) +
        "OutputDir=installer\n"
        "OutputBaseFilename={}-Setup\n".format(name) +
        "Compression=lzma\n"
        "SolidCompression=yes\n"
        "\n"
        "[Files]\n"
        'Source: "dist\\{}.exe"; DestDir: "{{app}}"; Flags: ignoreversion\n'.format(name) +
        "\n"
        "[Icons]\n"
        'Name: "{{commondesktop}}\\{} Desktop"; Filename: "{{app}}\\{}.exe"\n'.format(name, name) +
        'Name: "{{commonprograms}}\\UMOS\\{} Desktop"; Filename: "{{app}}\\{}.exe"\n'.format(name, name) +
        'Name: "{{commonprograms}}\\UMOS\\Uninstall UMOS"; Filename: "{{uninstallexe}}"\n'
        "\n"
        "[Run]\n"
        'Filename: "{{app}}\\{}.exe"; Description: "Launch UMOS Desktop"; Flags: postinstall nowait skipifsilent\n'.format(name),
        encoding="utf-8",
    )
    _info("[OK] Inno Setup script generated: {}".format(iss))


def _gen_dmg_setup(root: Path, name: str):
    """Generate a create-dmg.sh script for macOS."""
    sh = root / "create-dmg.sh"
    sh.write_text(
        "#!/usr/bin/env bash\n"
        "# Create macOS .dmg from built .app bundle.\n"
        "# Requires create-dmg (brew install create-dmg)\n"
        "set -euo pipefail\n"
        'APP="dist/{}.app"\n'.format(name) +
        'DMG="dist/{}-Setup.dmg"\n'.format(name) +
        'VOLUME="{} Desktop"\n'.format(name) +
        "\n"
        'if [ ! -d "$APP" ]; then\n'
        '    echo "Error: $APP not found. Run build_exe.py first." >&2\n'
        "    exit 1\n"
        "fi\n"
        "\n"
        'if command -v create-dmg &>/dev/null; then\n'
        "    create-dmg \\\n"
        '        --volname "$VOLUME" \\\n'
        '        --window-pos 200 120 \\\n'
        '        --window-size 800 400 \\\n'
        '        --icon-size 100 \\\n'
        '        --icon "$APP" 200 190 \\\n'
        '        --hide-extension "$APP" \\\n'
        '        --app-drop-link 600 185 \\\n'
        '        "$DMG" \\\n'
        '        "$APP"\n'
        '    echo "[OK] DMG created: $DMG"\n'
        "else\n"
        '    echo "create-dmg not found. App bundle is at $APP"' >&2\n"
        '    echo "Install create-dmg: brew install create-dmg" >&2\n'
        "fi\n",
        encoding="utf-8",
    )
    sh.chmod(0o755)
    _info("[OK] DMG script generated: {}".format(sh))


def _gen_linux_setup(root: Path, name: str):
    """Generate an AppDir for AppImage packaging."""
    appdir = root / "installer" / "UMOS.AppDir"
    appdir.mkdir(parents=True, exist_ok=True)

    desktop = appdir / "umos.desktop"
    desktop.write_text(
        "[Desktop Entry]\n"
        "Name=UMOS Desktop\n"
        "Comment=UniMind OS - AI Native Operating System\n"
        "Exec=UMOS-Desktop\n"
        "Icon=umos\n"
        "Terminal=false\n"
        "Type=Application\n"
        "Categories=Utility;Science;Development;\n",
        encoding="utf-8",
    )

    icon = appdir / "umos.png"
    if not icon.exists():
        # Create a minimal 1x1 PNG placeholder
        icon.write_bytes(
            b"\x89PNG\r\n\x1a\n"  # PNG signature
            b"\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
            b"\x08\x02\x00\x00\x00\x90wS\xde"
            b"\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f\x00\x00\x01\x01\x00\x05\x18\xd8N"
            b"\x00\x00\x00\x00IEND\xaeB`\x82"
        )

    run_sh = appdir / "AppRun"
    run_sh.write_text(
        "#!/usr/bin/env bash\n"
        'HERE="$(dirname "$(readlink -f "$0")")"\n'
        'exec "$HERE/UMOS-Desktop" "$@"\n',
        encoding="utf-8",
    )
    run_sh.chmod(0o755)

    _info("[OK] AppDir prepared: {}".format(appdir))
    _info("  To create AppImage, install appimagetool and run:")
    _info("  appimagetool {} installer/UMOS-Desktop-x86_64.AppImage".format(appdir))


if __name__ == "__main__":
    main()
