#!/usr/bin/env python3
"""Build UMOS Desktop as a standalone .exe with PyInstaller.

Usage:
    python build_exe.py              # one-file .exe (no console)
    python build_exe.py --console   # one-file .exe with console
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


def main():
    root = Path(__file__).resolve().parent
    args = sys.argv[1:]
    console = "--console" in args

    try:
        import PyInstaller  # noqa
    except ImportError:
        print("Installing PyInstaller...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])

    sep = ";" if sys.platform == "win32" else ":"

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", "UMOS-Desktop",
        "--noconfirm",
        "--clean",
        "--onefile",
    ]

    if not console:
        cmd.append("--windowed")

    # Add data dirs (each as SOURCE{DEST)
    for pkg in ("umos_py", "bridge", "quantum", "gui"):
        src = root / pkg
        if src.is_dir():
            cmd.append(f"--add-data={src}{sep}{pkg}")

    # Hidden imports for dynamic lookups
    for mod in ("umos_py", "bridge", "gui", "quantum"):
        cmd.append(f"--collect-submodules={mod}")

    # Entry point
    cmd.append(str(root / "gui" / "app.py"))

    print("Running PyInstaller...")
    print(f"  Command: {' '.join(cmd)}")
    subprocess.check_call(cmd, cwd=root)

    exe = root / "dist" / "UMOS-Desktop.exe"
    if exe.exists():
        size_mb = exe.stat().st_size / (1024 * 1024)
        print(f"\n[OK] Built: {exe} ({size_mb:.1f} MB)")
    else:
        print("\n[WARN] Expected exe not found.")
        dist_dir = root / "dist"
        if dist_dir.exists():
            for p in dist_dir.rglob("*"):
                if p.is_file():
                    print(f"  {p.relative_to(root)} ({p.stat().st_size / 1024:.0f} KB)")

    # Generate Inno Setup .iss
    _gen_innosetup(root)

    print("\nDone.")


def _gen_innosetup(root: Path):
    iss = root / "UMOS_installer.iss"
    content = f"""\
; UMOS Desktop Installer -- generated by build_exe.py
[Setup]
AppName=UniMind OS (UMOS) Desktop
AppVersion=0.2.0
DefaultDirName={{pf}}\\UMOS-Desktop
DefaultGroupName=UMOS
UninstallDisplayIcon={{app}}\\UMOS-Desktop.exe
OutputDir=installer
OutputBaseFilename=UMOS-Desktop-Setup
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\\UMOS-Desktop.exe"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{commondesktop}}\\UMOS Desktop"; Filename: "{{app}}\\UMOS-Desktop.exe"
Name: "{{commonprograms}}\\UMOS\\UMOS Desktop"; Filename: "{{app}}\\UMOS-Desktop.exe"
Name: "{{commonprograms}}\\UMOS\\Uninstall UMOS"; Filename: "{{uninstallexe}}"

[Run]
Filename: "{{app}}\\UMOS-Desktop.exe"; Description: "Launch UMOS Desktop"; Flags: postinstall nowait skipifsilent
"""
    iss.write_text(content, encoding="utf-8")
    print(f"[OK] Inno Setup script: {iss}")


if __name__ == "__main__":
    main()
