; UMOS Desktop Installer -- generated by build_exe.py
[Setup]
AppName=UniMind OS (UMOS) Desktop
AppVersion=0.2.0
DefaultDirName={commonpf}\UMOS-Desktop
DefaultGroupName=UMOS
UninstallDisplayIcon={app}\UMOS-Desktop.exe
OutputDir=installer
OutputBaseFilename=UMOS-Desktop-Setup
Compression=lzma
SolidCompression=yes

[Files]
Source: "dist\UMOS-Desktop.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{commondesktop}\UMOS Desktop"; Filename: "{app}\UMOS-Desktop.exe"
Name: "{commonprograms}\UMOS\UMOS Desktop"; Filename: "{app}\UMOS-Desktop.exe"
Name: "{commonprograms}\UMOS\Uninstall UMOS"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\UMOS-Desktop.exe"; Description: "Launch UMOS Desktop"; Flags: postinstall nowait skipifsilent
